on: pull_request

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Regenerate
      run: |
        npm ci
        npm start

    - name: Validate
      run: |
        jq --raw-output '.resources[].name' routes/api.github.com/github-rest-apis-for-insomnia.json

    - name: Stage, commit, and push changes
      if: startsWith(github.head_ref, 'greenkeeper/@octokit/routes')
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        HEAD_REF: ${{ github.head_ref }}
        COMMIT_MSG: |
          build: spec

          skip-checks: true
      run: |
        # Hard-code user config
        git config user.email "bots@wintron.codes"
        git config user.name "${GITHUB_REPOSITORY}[bot]"
        git config --get-regexp "user\.(name|email)"

        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

        # Checkout the branch so we can push back to it
        git checkout $HEAD_REF

        # Commit and push _just_ the specs
        git add routes/api.github.com/github-rest-apis-for-insomnia.json
        git commit routes/api.github.com/github-rest-apis-for-insomnia.json -m "${COMMIT_MSG}"
        git push --set-upstream origin "${HEAD_REF}"
